# Generated by Django 4.2.11 on 2024-10-30 18:51

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abordagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '3 Abordagens',
            },
        ),
        migrations.CreateModel(
            name='Apresentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sub_titulo', models.CharField(max_length=30)),
                ('sub_texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('foto', models.ImageField(upload_to='apresentacao/foto/')),
            ],
            options={
                'verbose_name_plural': '2 Apresentações',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='IndicesAbordagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('publicado', models.BooleanField(default=False)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=30)),
                ('abordagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.abordagem')),
            ],
            options={
                'verbose_name_plural': '3.1 Índices',
            },
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('icone', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '1.1 Redes Sociais',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '4 Tópicos',
            },
        ),
        migrations.CreateModel(
            name='TextosIndiceAbordagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_titulo', models.CharField(max_length=30)),
                ('sub_texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('publicado', models.BooleanField(default=False)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.indicesabordagem')),
            ],
            options={
                'verbose_name_plural': '3.2 Textos',
            },
        ),
        migrations.CreateModel(
            name='SubTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_titulo', models.CharField(max_length=30)),
                ('sub_texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('publicado', models.BooleanField(default=False)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.topico')),
            ],
            options={
                'verbose_name_plural': '4.1 Subtópicos',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('foto', models.ImageField(upload_to='home/foto/')),
                ('letreiro', models.JSONField(blank=True, null=True)),
                ('redes_sociais', models.ManyToManyField(to='dados.redesocial')),
            ],
            options={
                'verbose_name_plural': '1 HomePages',
            },
        ),
    ]
