# Generated by Django 4.2.11 on 2024-11-01 14:35

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bloco de Imagem',
                'verbose_name_plural': 'Blocos de Imagens',
            },
        ),
        migrations.CreateModel(
            name='GrupoExperiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('publicado', models.BooleanField(default=False)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('link', models.CharField(max_length=255)),
                ('imagem', models.ImageField(upload_to='')),
                ('experiencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.experiencia')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.grupoexperiencia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
