# Generated by Django 4.2.11 on 2024-11-05 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0003_abordagem_atual_apresentacao_atual_email_atual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name_plural': '4.1 Cards'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name_plural': '4 Experiências'},
        ),
        migrations.AlterModelOptions(
            name='grupoexperiencia',
            options={'verbose_name_plural': '4 A - Grupo Experiência'},
        ),
        migrations.AlterModelOptions(
            name='subtopico',
            options={'verbose_name_plural': '5.1 Subtópicos'},
        ),
        migrations.AlterModelOptions(
            name='topico',
            options={'verbose_name_plural': '5 Tópicos'},
        ),
        migrations.RemoveField(
            model_name='card',
            name='link',
        ),
    ]
