# Generated by Django 4.2.11 on 2024-05-20 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0003_apresentacao_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apresentacao',
            old_name='tub_titulo',
            new_name='sub_titulo',
        ),
    ]
