# Generated by Django 4.2.11 on 2024-11-05 16:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0004_alter_card_options_alter_experiencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='titulo',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
