# Generated by Django 4.2.11 on 2024-05-20 22:44

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0004_rename_tub_titulo_apresentacao_sub_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abordagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('texto', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Abordagens',
            },
        ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('publicado', models.BooleanField(default=False)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=30)),
                ('abordagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.abordagem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndiceAbordagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_titulo', models.CharField(max_length=30)),
                ('sub_texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('publicado', models.BooleanField(default=False)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.indice')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
