# Generated by Django 4.2.11 on 2024-06-09 19:28

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0006_topico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indice',
            options={'verbose_name_plural': 'Índices Abordagens'},
        ),
        migrations.AlterModelOptions(
            name='indiceabordagem',
            options={'verbose_name_plural': 'Textos Índices Abordagens'},
        ),
        migrations.CreateModel(
            name='SubTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_titulo', models.CharField(max_length=30)),
                ('sub_texto', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('publicado', models.BooleanField(default=False)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dados.topico')),
            ],
            options={
                'verbose_name_plural': 'Subtópicos',
            },
        ),
    ]
