# Generated by Django 4.2.11 on 2025-01-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0008_rename_publicado_card_exibindo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abordagem',
            options={'verbose_name_plural': '3 Abordagem'},
        ),
        migrations.AlterModelOptions(
            name='apresentacao',
            options={'verbose_name_plural': '2 Apresentação'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name_plural': '4.2 Card'},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'verbose_name_plural': 'Email'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name_plural': 'Endereço'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name_plural': '4 Experiência'},
        ),
        migrations.AlterModelOptions(
            name='grupoexperiencia',
            options={'verbose_name_plural': '4.1 Título Grupo Card'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name_plural': '1 HomePage'},
        ),
        migrations.AlterModelOptions(
            name='indicesabordagem',
            options={'verbose_name_plural': '3.1 Índice'},
        ),
        migrations.AlterModelOptions(
            name='redesocial',
            options={'verbose_name_plural': '1.1 Rede Social'},
        ),
        migrations.AlterModelOptions(
            name='subtopico',
            options={'verbose_name_plural': '5.1 Subtópico'},
        ),
        migrations.AlterModelOptions(
            name='telefone',
            options={'verbose_name_plural': 'Telefone'},
        ),
        migrations.AlterModelOptions(
            name='textosindiceabordagem',
            options={'verbose_name_plural': '3.2 Texto'},
        ),
        migrations.AlterModelOptions(
            name='topico',
            options={'verbose_name_plural': '5 Tópico'},
        ),
        migrations.RemoveField(
            model_name='indicesabordagem',
            name='atual',
        ),
        migrations.AlterField(
            model_name='home',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='home/foto/'),
        ),
    ]
